const map=L.map('map',{zoomControl:true,minZoom:8,maxZoom:19}).setView([13.99,-60.98],11);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);const saintLuciaBounds=[[13.70,-61.10],[14.30,-60.75]];map.setMaxBounds(saintLuciaBounds);
const busLayer=L.layerGroup().addTo(map);const stopLayer=L.layerGroup().addTo(map);const routeLayers={};const categoryLayers={Beauty:L.layerGroup(),Events:L.layerGroup(),Food:L.layerGroup(),['Getting Around']:L.layerGroup(),Lodging:L.layerGroup(),['Police Stations']:L.layerGroup()};Object.values(categoryLayers).forEach(l=>l.addTo(map));
const categoryColors={Beauty:'#d56a9c',Events:'#7b61b7',Food:'#e58a36','Getting Around':'#4d91c6',Lodging:'#5c9b72','Police Stations':'#4c5964'};
function markerIcon(category){return L.divIcon({className:'custom-marker',html:`<div style="width:28px;height:28px;border-radius:50%;background:${categoryColors[category]};border:3px solid white;box-shadow:0 2px 7px rgba(0,0,0,.35);display:grid;place-items:center;color:white;font-size:11px;font-weight:800">${category[0]}</div>`,iconSize:[28,28],iconAnchor:[14,14],popupAnchor:[0,-14]})}
function addPOI(category,name,lat,lng,description=''){return L.marker([lat,lng],{icon:markerIcon(category)}).bindPopup(`<div class="poi-popup"><h3>${name}</h3><p><b>${category}</b></p>${description?`<p>${description}</p>`:''}</div>`).addTo(categoryLayers[category])}
addPOI('Getting Around','Castries Bus Terminal',14.0107,-60.9897,'Central starting point for the bus network.');addPOI('Police Stations','Castries Police Station',14.0105,-60.9890,'Police station location.');
function addBusStops(data){if(!data?.features)return;L.geoJSON(data,{pointToLayer:(f,latlng)=>L.circleMarker(latlng,{radius:6,weight:2,color:'#fff',fillColor:'#2776b8',fillOpacity:.95}),onEachFeature:(f,l)=>{const p=f.properties||{};l.bindPopup(`<div class="poi-popup"><h3>${p.Destination||'Bus Stop'}</h3><p><b>Getting Around</b></p><p>Bus route stop: ${p.ID||''}</p></div>`);}}).addTo(stopLayer)}
if(typeof json_bus_stop_2!=='undefined')addBusStops(json_bus_stop_2);
function draw360Routes(){if(typeof busRoutes360==='undefined')return;busRoutes360.forEach(r=>{const layer=L.polyline(r.points,{color:r.color,weight:5,opacity:.95,lineCap:'round',lineJoin:'round'}).bindTooltip(`Route ${r.route} — ${r.name}`,{sticky:true}).bindPopup(`<div class="route-popup"><h3>Bus Route ${r.route}</h3><p>${r.name}</p></div>`);routeLayers[r.route]=layer;layer.addTo(busLayer)})}
draw360Routes();
function routeStyle(feature){const n=feature?.properties?.Name||'';const colors={'1A':'#1677d2','1B':'#1677d2','1D':'#1677d2','1E':'#1677d2','1F':'#1677d2','2A':'#16834a','2B':'#16834a','2C':'#16834a','2H':'#16834a','3A':'#f28b12','3B':'#f28b12','3C':'#f28b12','3D':'#f28b12','3E':'#f28b12','3F':'#f28b12','5A':'#6d2bb8','5B':'#6d2bb8','5C':'#6d2bb8','5D':'#6d2bb8','5E':'#6d2bb8','5F':'#6d2bb8'};return{color:colors[n]||'#2776b8',weight:4,opacity:.9}}
function addRoutes(data){if(!data?.features)return;L.geoJSON(data,{style:routeStyle,onEachFeature:(f,l)=>{const n=f.properties?.Name||'Bus route';const d=f.properties?.description||'';l.bindPopup(`<div class="route-popup"><h3>Bus Route ${n}</h3><p>${d}</p></div>`);l.bindTooltip(n,{sticky:true,className:'route-label'});}}).addTo(busLayer)}
if(typeof json_castries_busroute_1!=='undefined')addRoutes(json_castries_busroute_1);
document.getElementById('busBtn').addEventListener('click',e=>{const visible=map.hasLayer(busLayer);[busLayer,stopLayer].forEach(l=>visible?map.removeLayer(l):l.addTo(map));e.currentTarget.setAttribute('aria-pressed',String(!visible))});
document.querySelectorAll('.route-key button').forEach(btn=>btn.addEventListener('click',()=>{const r=btn.dataset.route;const layer=routeLayers[r];if(!layer)return;if(map.hasLayer(layer)){map.removeLayer(layer);btn.classList.add('muted')}else{layer.addTo(busLayer);btn.classList.remove('muted')}}));
document.querySelectorAll('.key-item').forEach(btn=>btn.addEventListener('click',()=>{const c=btn.dataset.category;const layer=categoryLayers[c];if(map.hasLayer(layer)){map.removeLayer(layer);btn.classList.remove('active')}else{layer.addTo(map);btn.classList.add('active')}}));document.getElementById('resetBtn').addEventListener('click',()=>map.fitBounds(saintLuciaBounds));document.getElementById('locateBtn').addEventListener('click',()=>map.locate({setView:true,maxZoom:16,enableHighAccuracy:true}));map.on('locationerror',()=>alert('Your location could not be determined. Please allow location access in your browser.'));
